### ISSUE TITLE
Plotting style improvement 

### ISSUE THREAD

**Issue by ltgio** [jameshtwose/finance-dashboard#7]
Time series plot such as this one could be improved.

![Screen Shot 2022-11-21 at 14 11 06](https://user-images.githubusercontent.com/51316429/203063943-d8c12507-832b-4143-9dfd-7f55ce1cb362.png)

**Comment by jameshtwose** [comment]
Yeah the issue is that ING does not provide the full timestamp (only to the day level) so it will stack the values from the same day on top of each other. There are two possible ways of dealing with this:
- artificially jittering the day by adding random hours/ minutes
- or using a mean and confidence intervals kind of setup (not sure how I feel about this as you lose the informative hover info this way :/)
